### ISSUE TITLE
awesome corner case: submitting valid blueprint for deployment as form-encoded spawns two deployments

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp-core#3]
Don't ask me how I found this out. POST a valid blueprint as JSON to /deployments but with the Content-Type as `application/x-www-form-urlencoded`  spawns two/2 valid, individual deployments. This does cause some havoc further down the road in Vamp-router. 

Real issue: reject anything not encoded as json or yaml.

**Comment by dragoslav** [comment]
For Rest API we support only: application/json & application/x-yaml
