### ISSUE TITLE
Using `offload` makes actor blocking

### ISSUE THREAD

**Issue by jgordijn** [magneticio/vamp-core#6]
When using `ReplyActor` the interface forces to implement `protected def reply(request: Any): Any` This means that you have to block when you need to do any IO and wait on a future to complete. The `offload` function facilitates this and call `Await.result` (see https://github.com/magneticio/vamp-common/issues/4).

**Comment by dragoslav** [comment]
Will be solved as part of https://github.com/magneticio/vamp/issues/239
