### ISSUE TITLE
ui has hardcoded API_URL=http://192.168.59.103:8080/api/v1   in app.js

### ISSUE THREAD

**Issue by metskem-rabo** [magneticio/vamp-core#8]
Trying out the ui I got myself an empty screen. Viewing source and inspecting app.js I found there are 2 hardcoded API_URL's to http://192.168.59.103:8080/api/v1 

Changed that to /api/v1 and zipped up the vamp-core.jar and now see my blueprints.

**Comment by danielsneijers** [comment]
That is correct. The UI is currently 'hidden', as in: we are developing and testing a lot to catch these problems before releasing. At the moment your workaround should suffice, but the next version of the UI will be bundled soon, and will have the option to change your API endpoint uri from the interface.

**Comment by danielsneijers** [comment]
With the release of the UI bundled in Vamp v0.7.9 the API_URL is now editable by the user. This would solve your problem so I'm closing the issue.
